spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew_postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/monew_mongo
#logging:
#  level:
#    root: debug