spring:
  ### Spring batch를 위해 추가된 내용
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  ###
  profiles:
    active: dev ## 설정

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('yg-tech-spring-boot-jwt-monew-secret-sb01-part3-tech-spring-boot-jwt-monew-secret'))
  secret: eWctdGVjaC1zcHJpbmctYm9vdC1qd3QtbW9uZXctc2VjcmV0LXNiMDEtcGFydDMtdGVjaC1zcHJpbmctYm9vdC1qd3QtbW9uZXctc2VjcmV0
  token-validity-in-seconds: 86400

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

monew:
  storage:
    type: local
    local:
      root-path: ./monew/storage
    #s3:
    #  bucket: ${AWS_S3_BUCKET}
    #credentials:
    #  access-key: ${AWS_S3_ACCESS_KEY}
    #  secret-key: ${AWS_S3_SECRET_KEY}
    #region:
    #  static-region: ${AWS_S3_REGION}
